### STAGE 1: Build ###
FROM node AS build
WORKDIR  /usr/src/app
COPY package*.json ./

#RUN npm install
RUN npm install -g @angular/cli

RUN npm install
COPY . .

### STAGE 2: Run ###
CMD ["ng", "serve", "--host=0.0.0.0", "--disable-host-check"]
